use std::rc::Rc;

use chrono::NaiveDate;
use serde::{Deserialize, Serialize};

use crate::snp_impl::get_snp;
use snp_mod_io::snp as io;

#[derive(Debug, Serialize, Deserialize)]
pub enum SnpTicker {
    Available(io::SnP),
    Empty,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct SnPUpdate {
    pub date: NaiveDate,
    pub added_ticker: SnpTicker,
    added_security: Rc<str>,
    pub removed_ticker: SnpTicker,
    removed_security: Rc<str>,
    reason: Rc<str>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct SnPUpdateUnformatted<'a> {
    date: &'a str,
    added_ticker: &'a str,
    added_security: &'a str,
    removed_ticker: &'a str,
    removed_security: &'a str,
    reason: &'a str,
}

pub fn get_all_updates() -> [SnPUpdate; 338] {
    let updates = format_all_updates(get_all_updates_unformatted()).unwrap();
    let boxed_slice = updates.into_boxed_slice();
    let boxed_array: Box<[SnPUpdate; 338]> = match boxed_slice.try_into() {
        Ok(ba) => ba,
        Err(o) => panic!("Expected a Vec of length {} but it was {}", 338, o.len()),
    };
    *boxed_array
}

pub fn format_all_updates(
    updates_unformatted: Vec<SnPUpdateUnformatted<'_>>,
) -> Result<Vec<SnPUpdate>, Error> {
    let updates = updates_unformatted.iter().map(format_update).collect();
    updates
}

#[derive(Debug, thiserror::Error)]
pub enum Error {
    #[error("{0}")]
    ParseError(#[from] chrono::ParseError),
    #[error("{0}")]
    SnPGetError(#[from] io::Error),
}

fn format_update<'a>(update: &SnPUpdateUnformatted<'a>) -> Result<SnPUpdate, Error> {
    let format = "%B %e, %Y";
    let date: NaiveDate = NaiveDate::parse_from_str(update.date, format)
        .map_err(|e| {
            println!("parsing error happened: '{}'", update.date);
            Error::ParseError(e)
        })?
        .into();

    let added_ticker = if update.added_ticker == "" {
        SnpTicker::Empty
    } else {
        let ticker = get_snp(update.added_ticker).map_err(|e| {
            println!("parsing error happened: '{}'", update.added_ticker);
            Error::SnPGetError(e)
        })?;
        SnpTicker::Available(ticker)
    };

    let removed_ticker = if update.removed_ticker == "" {
        SnpTicker::Empty
    } else {
        let ticker = get_snp(update.removed_ticker).map_err(|e| {
            println!("parsing error happened: '{}'", update.removed_ticker);
            Error::SnPGetError(e)
        })?;
        SnpTicker::Available(ticker)
    };

    let new_update = SnPUpdate {
        date,
        added_ticker,
        added_security: Rc::<str>::from(update.added_security),
        removed_ticker,
        removed_security: Rc::<str>::from(update.removed_security),
        reason: Rc::<str>::from(update.reason),
    };
    Ok(new_update)
}

pub fn get_all_updates_unformatted() -> Vec<SnPUpdateUnformatted<'static>> {
    let updates_unformatted = vec![
        SnPUpdateUnformatted { date: "December 18, 2023", added_ticker: "UBER", added_security: "Uber", removed_ticker: "SEE", removed_security: "Sealed Air ", reason: "Market capitalization change.[4]", },
        SnPUpdateUnformatted { date: "December 18, 2023", added_ticker: "JBL", added_security: "Jabil", removed_ticker: "ALK", removed_security: "Alaska Air Group ", reason: "Market capitalization change.[4]", },
        SnPUpdateUnformatted { date: "December 18, 2023", added_ticker: "BLDR", added_security: "Builders FirstSource", removed_ticker: "SEDG", removed_security: "SolarEdge ", reason: "Market capitalization change.[4]", },
        SnPUpdateUnformatted { date: "October 18, 2023", added_ticker: "HUBB", added_security: "Hubbell", removed_ticker: "OGN", removed_security: "Organon & Co. ", reason: "Market capitalization change.[5]", },
        SnPUpdateUnformatted { date: "October 18, 2023", added_ticker: "LULU", added_security: "Lululemon Athletica", removed_ticker: "ATVI", removed_security: "Activision Blizzard ", reason: "S&P 500 and S&P 100 constituent Microsoft acquired Activision Blizzard.[5]", },
        SnPUpdateUnformatted { date: "October 3, 2023", added_ticker: "", added_security: "", removed_ticker: "DXC", removed_security: "DXC Technology", reason: "Market capitalization change.[6]", },
        SnPUpdateUnformatted { date: "October 2, 2023", added_ticker: "VLTO", added_security: "Veralto", removed_ticker: "", removed_security: "", reason: "S&P 500 and S&P 100 constituent Danaher Corporation is spinning off Veralto.[6]", },
        SnPUpdateUnformatted { date: "September 18, 2023", added_ticker: "BX", added_security: "Blackstone", removed_ticker: "LNC", removed_security: "Lincoln National Corporation ", reason: "Market capitalization change.[7]", },
        SnPUpdateUnformatted { date: "September 18, 2023", added_ticker: "ABNB", added_security: "Airbnb", removed_ticker: "NWL", removed_security: "Newell Brands ", reason: "Market capitalization change.[7]", },
        SnPUpdateUnformatted { date: "August 25, 2023", added_ticker: "KVUE", added_security: "Kenvue", removed_ticker: "AAP", removed_security: "Advance Auto Parts ", reason: "S&P 500 and S&P 100 constituent Johnson & Johnson offered to exchange the shares of Kenvue held for shares of Johnson & Johnson in a split-off exchange offer.[8]", },
        SnPUpdateUnformatted { date: "June 20, 2023", added_ticker: "PANW", added_security: "Palo Alto Networks", removed_ticker: "DISH", removed_security: "Dish Network ", reason: "Market capitalization change.[9]", },
        SnPUpdateUnformatted { date: "May 4, 2023", added_ticker: "AXON", added_security: "Axon Enterprise", removed_ticker: "FRC", removed_security: "First Republic Bank ", reason: "The Federal Deposit Insurance Corporation (FDIC) placed First Republic Bank into FDIC Receivership.[10]", },
        SnPUpdateUnformatted { date: "March 20, 2023", added_ticker: "FICO", added_security: "Fair Isaac", removed_ticker: "LUMN", removed_security: "Lumen Technologies ", reason: "Market capitalization change.[11]", },
        SnPUpdateUnformatted { date: "March 15, 2023", added_ticker: "BG", added_security: "Bunge Global", removed_ticker: "SBNY", removed_security: "Signature Bank ", reason: "The FDIC placed Signature Bank into FDIC Receivership.[12]", },
        SnPUpdateUnformatted { date: "March 15, 2023", added_ticker: "PODD", added_security: "Insulet", removed_ticker: "SIVB", removed_security: "SVB Financial Group ", reason: "The FDIC placed SVB's main subsidiary, Silicon Valley Bank, into receivership.[13]", },
        SnPUpdateUnformatted { date: "January 5, 2023", added_ticker: "", added_security: "", removed_ticker: "VNO", removed_security: "Vornado Realty Trust", reason: "Market capitalization change.[14]", },
        SnPUpdateUnformatted { date: "January 4, 2023", added_ticker: "GEHC", added_security: "GE HealthCare", removed_ticker: "", removed_security: "", reason: "S&P 500 constituent General Electric spun off GE HealthCare.[15]", },
        SnPUpdateUnformatted { date: "December 22, 2022", added_ticker: "STLD", added_security: "Steel Dynamics", removed_ticker: "ABMD", removed_security: "Abiomed ", reason: "S&P 500 constituent Johnson & Johnson acquired Abiomed.[16]", },
        SnPUpdateUnformatted { date: "December 19, 2022", added_ticker: "FSLR", added_security: "First Solar", removed_ticker: "FBHS", removed_security: "Fortune Brands Home & Security ", reason: "Market capitalization change.[17]", },
        SnPUpdateUnformatted { date: "December 19, 2022", added_ticker: "", added_security: "", removed_ticker: "MBC", removed_security: "MasterBrand", reason: "Market capitalization change.[17]", },
        SnPUpdateUnformatted { date: "December 15, 2022", added_ticker: "MBC", added_security: "MasterBrand", removed_ticker: "", removed_security: "", reason: "S&P 500 constituent Fortune Brands Home & Security spun off MasterBrand.[17]", },
        SnPUpdateUnformatted { date: "November 1, 2022", added_ticker: "ACGL", added_security: "Arch Capital Group", removed_ticker: "TWTR", removed_security: "Twitter ", reason: "Elon Musk acquired Twitter.[18]", },
        SnPUpdateUnformatted { date: "October 12, 2022", added_ticker: "TRGP", added_security: "Targa Resources", removed_ticker: "NLSN", removed_security: "Nielsen Holdings ", reason: "Elliot Management Corp acquired Nielsen Holdings.[19]", },
        SnPUpdateUnformatted { date: "October 3, 2022", added_ticker: "PCG", added_security: "PG&E", removed_ticker: "CTXS", removed_security: "Citrix Systems ", reason: "Vista Equity Partners acquired Citrix Systems.[20]", },
        SnPUpdateUnformatted { date: "October 3, 2022", added_ticker: "EQT", added_security: "EQT", removed_ticker: "DRE", removed_security: "Duke Realty ", reason: "S&P 500 constituent Prologis Inc. acquired Duke Realty.[20]", },
        SnPUpdateUnformatted { date: "September 19, 2022", added_ticker: "CSGP", added_security: "CoStar Group", removed_ticker: "PVH", removed_security: "PVH ", reason: "Market capitalization change.[21]", },
        SnPUpdateUnformatted { date: "September 19, 2022", added_ticker: "INVH", added_security: "Invitation Homes", removed_ticker: "PENN", removed_security: "Penn Entertainment ", reason: "Market capitalization change.[21]", },
        SnPUpdateUnformatted { date: "June 21, 2022", added_ticker: "", added_security: "", removed_ticker: "UA", removed_security: "Under Armour (Class C)", reason: "Market capitalization change.[22]", },
        SnPUpdateUnformatted { date: "June 21, 2022", added_ticker: "KDP", added_security: "Keurig Dr Pepper", removed_ticker: "UAA", removed_security: "Under Armour (Class A) ", reason: "Market capitalization change.[22]", },
        SnPUpdateUnformatted { date: "June 21, 2022", added_ticker: "ON", added_security: "ON Semiconductor", removed_ticker: "IPGP", removed_security: "IPG Photonics ", reason: "Market capitalization change.[22]", },
        SnPUpdateUnformatted { date: "June 8, 2022", added_ticker: "VICI", added_security: "Vici Properties", removed_ticker: "CERN", removed_security: "Cerner ", reason: "S&P 500 constituent Oracle Corp. acquired Cerner.[22]", },
        SnPUpdateUnformatted { date: "April 4, 2022", added_ticker: "CPT", added_security: "Camden Property Trust", removed_ticker: "PBCT", removed_security: "People's United Financial ", reason: "S&P 500 constituent M&T Bank Corp. acquired People's United Financial.[23]", },
        SnPUpdateUnformatted { date: "March 2, 2022", added_ticker: "MOH", added_security: "Molina Healthcare", removed_ticker: "INFO", removed_security: "IHS Markit ", reason: "S&P 500 constituent S&P Global Inc. acquired IHS Markit.[24]", },
        SnPUpdateUnformatted { date: "February 15, 2022", added_ticker: "NDSN", added_security: "Nordson Corporation", removed_ticker: "XLNX", removed_security: "Xilinx ", reason: "S&P 500 constituent Advanced Micro Devices acquired Xilinx.[25]", },
        SnPUpdateUnformatted { date: "February 3, 2022", added_ticker: "", added_security: "", removed_ticker: "GPS", removed_security: "Gap", reason: "Market capitalization change.[26]", },
        SnPUpdateUnformatted { date: "February 2, 2022", added_ticker: "CEG", added_security: "Constellation Energy", removed_ticker: "", removed_security: "", reason: "S&P 500 and 100 constituent Exelon Corp. spun off Constellation Energy.[26]", },
        SnPUpdateUnformatted { date: "December 20, 2021", added_ticker: "SBNY", added_security: "Signature Bank", removed_ticker: "LEG", removed_security: "Leggett & Platt ", reason: "Market capitalization change.[27]", },
        SnPUpdateUnformatted { date: "December 20, 2021", added_ticker: "SEDG", added_security: "SolarEdge", removed_ticker: "HBI", removed_security: "Hanesbrands ", reason: "Market capitalization change.[27]", },
        SnPUpdateUnformatted { date: "December 20, 2021", added_ticker: "FDS", added_security: "FactSet", removed_ticker: "WU", removed_security: "Western Union ", reason: "Market capitalization change.[27]", },
        SnPUpdateUnformatted { date: "December 14, 2021", added_ticker: "EPAM", added_security: "EPAM Systems", removed_ticker: "KSU", removed_security: "Kansas City Southern ", reason: "Canadian Pacific acquired Kansas City Southern.[28]", },
        SnPUpdateUnformatted { date: "September 20, 2021", added_ticker: "MTCH", added_security: "Match Group", removed_ticker: "PRGO", removed_security: "Perrigo ", reason: "Market capitalization change.[29]", },
        SnPUpdateUnformatted { date: "September 20, 2021", added_ticker: "CDAY", added_security: "Ceridian", removed_ticker: "UNM", removed_security: "Unum ", reason: "Market capitalization change.[29]", },
        SnPUpdateUnformatted { date: "September 20, 2021", added_ticker: "BRO", added_security: "Brown & Brown", removed_ticker: "NOV", removed_security: "Nov ", reason: "Market capitalization change.[29]", },
        SnPUpdateUnformatted { date: "August 30, 2021", added_ticker: "TECH", added_security: "Bio-Techne", removed_ticker: "MXIM", removed_security: "Maxim Integrated ", reason: "S&P 500 constituent Analog Devices acquired Maxim Integrated Products.[30]", },
        SnPUpdateUnformatted { date: "July 21, 2021", added_ticker: "MRNA", added_security: "Moderna", removed_ticker: "ALXN", removed_security: "Alexion Pharmaceuticals ", reason: "AstraZeneca acquired Alexion Pharmaceuticals.[31]", },
        SnPUpdateUnformatted { date: "June 4, 2021", added_ticker: "", added_security: "", removed_ticker: "HFC", removed_security: "HollyFrontier", reason: "Market capitalization change.[32]", },
        SnPUpdateUnformatted { date: "June 3, 2021", added_ticker: "OGN", added_security: "Organon & Co.", removed_ticker: "", removed_security: "", reason: "S&P 500/100 constituent Merck & Co. spun off Organon.[32]", },
        SnPUpdateUnformatted { date: "May 14, 2021", added_ticker: "CRL", added_security: "Charles River Laboratories", removed_ticker: "FLIR", removed_security: "FLIR Systems ", reason: "S&P 500 constituent Teledyne Technologies acquired FLIR Systems.[33]", },
        SnPUpdateUnformatted { date: "April 20, 2021", added_ticker: "PTC", added_security: "PTC", removed_ticker: "VAR", removed_security: "Varian Medical Systems ", reason: "Siemens Healthineers acquired Varian Medical Systems.[34]", },
        SnPUpdateUnformatted { date: "March 22, 2021", added_ticker: "NXPI", added_security: "NXP", removed_ticker: "FLS", removed_security: "Flowserve ", reason: "Market capitalization change.[35]", },
        SnPUpdateUnformatted { date: "March 22, 2021", added_ticker: "PENN", added_security: "Penn National Gaming", removed_ticker: "SLG", removed_security: "SL Green Realty ", reason: "Market capitalization change.[35]", },
        SnPUpdateUnformatted { date: "March 22, 2021", added_ticker: "GNRC", added_security: "Generac Holdings", removed_ticker: "XRX", removed_security: "Xerox ", reason: "Market capitalization change.[35]", },
        SnPUpdateUnformatted { date: "March 22, 2021", added_ticker: "CZR", added_security: "Caesars Entertainment", removed_ticker: "VNT", removed_security: "Vontier ", reason: "Market capitalization change.[35]", },
        SnPUpdateUnformatted { date: "February 12, 2021", added_ticker: "MPWR", added_security: "Monolithic Power Systems", removed_ticker: "FTI", removed_security: "TechnipFMC ", reason: "TechnipFMC was removed from the S&P 500 in anticipation of its announced spin-off of Technip Energies.[36]", },
        SnPUpdateUnformatted { date: "January 21, 2021", added_ticker: "TRMB", added_security: "Trimble", removed_ticker: "CXO", removed_security: "Concho Resources ", reason: "S&P 500/100 constituent ConocoPhillips acquired Concho Resources.[37]", },
        SnPUpdateUnformatted { date: "January 7, 2021", added_ticker: "ENPH", added_security: "Enphase Energy", removed_ticker: "TIF", removed_security: "Tiffany & Co ", reason: "LVMH Moet Hennessy-Louis Vuitton SE acquired Tiffany & Co.[38]", },
        SnPUpdateUnformatted { date: "December 21, 2020", added_ticker: "TSLA", added_security: "Tesla", removed_ticker: "AIV", removed_security: "Apartment Investment & Management ", reason: "Apartment Investment and Management (Aimco) spun off Apartment Income REIT.[39]", },
        SnPUpdateUnformatted { date: "October 12, 2020", added_ticker: "", added_security: "", removed_ticker: "NBL", removed_security: "Noble Energy", reason: "Chevron acquired Noble Energy.[40]", },
        SnPUpdateUnformatted { date: "October 9, 2020", added_ticker: "VNT", added_security: "Vontier", removed_ticker: "", removed_security: "", reason: "S&P 500 constituent Fortive spun off Vontier.[40]", },
        SnPUpdateUnformatted { date: "October 7, 2020", added_ticker: "POOL", added_security: "Pool Corporation", removed_ticker: "ETFC", removed_security: "E-Trade ", reason: "Morgan Stanley acquired E*Trade.[41]", },
        SnPUpdateUnformatted { date: "September 21, 2020", added_ticker: "ETSY", added_security: "Etsy", removed_ticker: "HRB", removed_security: "H&R Block ", reason: "Market capitalization change.[42]", },
        SnPUpdateUnformatted { date: "September 21, 2020", added_ticker: "TER", added_security: "Teradyne", removed_ticker: "COTY", removed_security: "Coty ", reason: "Market capitalization change.[42]", },
        SnPUpdateUnformatted { date: "September 21, 2020", added_ticker: "CTLT", added_security: "Catalent", removed_ticker: "KSS", removed_security: "Kohl's ", reason: "Market capitalization change.[42]", },
        SnPUpdateUnformatted { date: "June 22, 2020", added_ticker: "BIO", added_security: "Bio-Rad Laboratories", removed_ticker: "ADS", removed_security: "Alliance Data Systems ", reason: "Market capitalization change.[43]", },
        SnPUpdateUnformatted { date: "June 22, 2020", added_ticker: "TDY", added_security: "Teledyne", removed_ticker: "HOG", removed_security: "Harley-Davidson ", reason: "Market capitalization change.[43]", },
        SnPUpdateUnformatted { date: "June 22, 2020", added_ticker: "TYL", added_security: "Tyler Technologies", removed_ticker: "JWN", removed_security: "Nordstrom ", reason: "Market capitalization change.[43]", },
        SnPUpdateUnformatted { date: "May 22, 2020", added_ticker: "WST", added_security: "West Pharmaceutical Services", removed_ticker: "HP", removed_security: "Helmerich & Payne ", reason: "Market capitalization change.[44]", },
        SnPUpdateUnformatted { date: "May 12, 2020", added_ticker: "DPZ", added_security: "Domino's Pizza", removed_ticker: "CPRI", removed_security: "Capri Holdings ", reason: "Market capitalization change.[45]", },
        SnPUpdateUnformatted { date: "May 12, 2020", added_ticker: "DXCM", added_security: "Dexcom", removed_ticker: "AGN", removed_security: "Allergan ", reason: "Allergan acquired by AbbVie.[45]", },
        SnPUpdateUnformatted { date: "April 6, 2020", added_ticker: "", added_security: "", removed_ticker: "M", removed_security: "Macy's", reason: "Market capitalization change.[46]", },
        SnPUpdateUnformatted { date: "April 6, 2020", added_ticker: "", added_security: "", removed_ticker: "RTN", removed_security: "Raytheon Company", reason: "United Technologies spun off Otis and Carrier and acquired Raytheon Company.[46]", },
        SnPUpdateUnformatted { date: "April 3, 2020", added_ticker: "OTIS", added_security: "Otis Worldwide", removed_ticker: "", removed_security: "", reason: "United Technologies spun off Otis and Carrier and acquired Raytheon Company.[46]", },
        SnPUpdateUnformatted { date: "April 3, 2020", added_ticker: "CARR", added_security: "Carrier", removed_ticker: "", removed_security: "", reason: "United Technologies spun off Otis and Carrier and acquired Raytheon Company.[46]", },
        SnPUpdateUnformatted { date: "April 1, 2020", added_ticker: "HWM", added_security: "Howmet Aerospace", removed_ticker: "ARNC", removed_security: "Arconic ", reason: "Arconic separated into 2 companies - Howmet remained on the index.[47]", },
        SnPUpdateUnformatted { date: "March 2, 2020", added_ticker: "IR", added_security: "Ingersoll Rand", removed_ticker: "XEC", removed_security: "Cimarex Energy ", reason: "Gardner Denver acquired Ingersoll Rand's industrial businesses then changed its name to the \"new\" Ingersoll Rand Inc.[48][49]", },
        SnPUpdateUnformatted { date: "January 28, 2020", added_ticker: "PAYC", added_security: "Paycom", removed_ticker: "WCG", removed_security: "WellCare ", reason: "S&P 500 constituent Centene Corp. (NYSE: CNC) acquired Wellcare Health Plans.[50]", },
        SnPUpdateUnformatted { date: "December 23, 2019", added_ticker: "LYV", added_security: "Live Nation Entertainment", removed_ticker: "AMG", removed_security: "Affiliated Managers Group ", reason: "Market capitalization change.[51]", },
        SnPUpdateUnformatted { date: "December 23, 2019", added_ticker: "ZBRA", added_security: "Zebra Technologies", removed_ticker: "TRIP", removed_security: "TripAdvisor ", reason: "Market capitalization change.[51]", },
        SnPUpdateUnformatted { date: "December 23, 2019", added_ticker: "STE", added_security: "Steris", removed_ticker: "MAC", removed_security: "Macerich ", reason: "Market capitalization change.[51]", },
        SnPUpdateUnformatted { date: "December 9, 2019", added_ticker: "ODFL", added_security: "Old Dominion Freight Line", removed_ticker: "STI", removed_security: "SunTrust Banks ", reason: "BB&T acquired SunTrust to form Truist Financial.[52]", },
        SnPUpdateUnformatted { date: "December 5, 2019", added_ticker: "WRB", added_security: "W. R. Berkley Corporation", removed_ticker: "VIAB", removed_security: "Viacom ", reason: "CBS acquired Viacom to form ViacomCBS.[53]", },
        SnPUpdateUnformatted { date: "November 21, 2019", added_ticker: "NOW", added_security: "ServiceNow", removed_ticker: "CELG", removed_security: "Celgene ", reason: "Bristol-Myers Squibb (NYSE:BMY) acquired Celgene.[54]", },
        SnPUpdateUnformatted { date: "October 3, 2019", added_ticker: "LVS", added_security: "Las Vegas Sands", removed_ticker: "NKTR", removed_security: "Nektar Therapeutics ", reason: "Market capitalization change.[55]", },
        SnPUpdateUnformatted { date: "September 26, 2019", added_ticker: "NVR", added_security: "NVR", removed_ticker: "JEF", removed_security: "Jefferies Financial Group ", reason: "JEF spun off SPB.[56]", },
        SnPUpdateUnformatted { date: "September 23, 2019", added_ticker: "CDW", added_security: "CDW", removed_ticker: "TSS", removed_security: "TSYS ", reason: "S&P 500 constituent Global Payments (NYSE: GPN) acquired TSS.[57]", },
        SnPUpdateUnformatted { date: "August 9, 2019", added_ticker: "LDOS", added_security: "Leidos", removed_ticker: "APC", removed_security: "Anadarko Petroleum ", reason: "S&P 500 & 100 constituent Occidental Petroleum Corp. (NYSE:OXY) acquired Anadarko Petroleum.[58]", },
        SnPUpdateUnformatted { date: "August 9, 2019", added_ticker: "IEX", added_security: "IDEX Corporation", removed_ticker: "FL", removed_security: "Foot Locker ", reason: "Market capitalization change.[58]", },
        SnPUpdateUnformatted { date: "July 15, 2019", added_ticker: "TMUS", added_security: "T-Mobile US", removed_ticker: "RHT", removed_security: "Red Hat ", reason: "S&P 500 & 100 constituent IBM acquired Red Hat.[59]", },
        SnPUpdateUnformatted { date: "July 1, 2019", added_ticker: "MKTX", added_security: "MarketAxess", removed_ticker: "LLL", removed_security: "L3 Technologies ", reason: "L3 purchased by Harris Corporation[60]", },
        SnPUpdateUnformatted { date: "June 11, 2019", added_ticker: "AMCR", added_security: "Amcor", removed_ticker: "BMS", removed_security: "Bemis ", reason: "BMS changed to AMCR post merger with Amcor;[61] subsequently renamed to Amcor[62]", },
        SnPUpdateUnformatted { date: "June 7, 2019", added_ticker: "BMS", added_security: "Bemis", removed_ticker: "MAT", removed_security: "Mattel ", reason: "Pending merger of Bemis and Amcor; Bemis treated as the surviving entity.[63]", },
        SnPUpdateUnformatted { date: "June 3, 2019", added_ticker: "DD", added_security: "DuPont", removed_ticker: "DWDP", removed_security: "DuPont ", reason: "DWDP changed to DD after spinning off Corteva.[64]", },
        SnPUpdateUnformatted { date: "June 3, 2019", added_ticker: "CTVA", added_security: "Corteva", removed_ticker: "FLR", removed_security: "Fluor Corporation ", reason: "CTVA spun off from DWDP (which then changed symbol to DD)[64]", },
        SnPUpdateUnformatted { date: "April 2, 2019", added_ticker: "DOW", added_security: "Dow", removed_ticker: "BHF", removed_security: "Brighthouse Financial ", reason: "DOW spun off from DWDP[65]", },
        SnPUpdateUnformatted { date: "February 27, 2019", added_ticker: "WAB", added_security: "Wabtec", removed_ticker: "GT", removed_security: "The Goodyear Tire & Rubber Company ", reason: "WAB acquired GE transportation business[66]", },
        SnPUpdateUnformatted { date: "February 15, 2019", added_ticker: "ATO", added_security: "Atmos Energy", removed_ticker: "NFX", removed_security: "Newfield Exploration ", reason: "ECA acquired NFX[67]", },
        SnPUpdateUnformatted { date: "January 18, 2019", added_ticker: "TFX", added_security: "Teleflex", removed_ticker: "PCG", removed_security: "Pacific Gas & Electric Company ", reason: "PCG filed for bankruptcy[68]", },
        SnPUpdateUnformatted { date: "January 2, 2019", added_ticker: "FRC", added_security: "First Republic Bank", removed_ticker: "SCG", removed_security: "SCANA ", reason: "Dominion Energy acquired SCANA Corporation[69]", },
        SnPUpdateUnformatted { date: "December 24, 2018", added_ticker: "CE", added_security: "Celanese", removed_ticker: "ESRX", removed_security: "Express Scripts ", reason: "S&P 500 constituent Cigna (NYSE: CI) acquired ESRX[70]", },
        SnPUpdateUnformatted { date: "December 3, 2018", added_ticker: "LW", added_security: "Lamb Weston", removed_ticker: "COL", removed_security: "Rockwell Collins ", reason: "UTX acquired COL[71]", },
        SnPUpdateUnformatted { date: "December 3, 2018", added_ticker: "MXIM", added_security: "Maxim Integrated", removed_ticker: "AET", removed_security: "Aetna ", reason: "CVS acquired Aetna[71]", },
        SnPUpdateUnformatted { date: "December 3, 2018", added_ticker: "FANG", added_security: "Diamondback Energy", removed_ticker: "SRCL", removed_security: "Stericycle ", reason: "Market Capitalization change[71]", },
        SnPUpdateUnformatted { date: "November 13, 2018", added_ticker: "JKHY", added_security: "Jack Henry & Associates", removed_ticker: "EQT", removed_security: "EQT ", reason: "EQT spun off ETRN[72]", },
        SnPUpdateUnformatted { date: "November 6, 2018", added_ticker: "KEYS", added_security: "Keysight", removed_ticker: "CA", removed_security: "CA Technologies ", reason: "CA acquired by Broadcom.[73]", },
        SnPUpdateUnformatted { date: "October 11, 2018", added_ticker: "FTNT", added_security: "Fortinet", removed_ticker: "EVHC", removed_security: "Envision Healthcare ", reason: "EVHC acquired by KKR.[74]", },
        SnPUpdateUnformatted { date: "October 1, 2018", added_ticker: "ROL", added_security: "Rollins", removed_ticker: "ANDV", removed_security: "Andeavor ", reason: "ANDV acquired by Marathon Petroleum.[75]", },
        SnPUpdateUnformatted { date: "September 14, 2018", added_ticker: "WCG", added_security: "WellCare", removed_ticker: "XL", removed_security: "XL Group ", reason: "XL acquired by AXA.[76]", },
        SnPUpdateUnformatted { date: "August 28, 2018", added_ticker: "ANET", added_security: "Arista Networks", removed_ticker: "GGP", removed_security: "GGP ", reason: "GGP acquired by Brookfield Property Partners.[77]", },
        SnPUpdateUnformatted { date: "July 2, 2018", added_ticker: "CPRT", added_security: "Copart", removed_ticker: "DPS", removed_security: "Dr Pepper Snapple Group ", reason: "DPS acquired by Keurig Green Mountain.[78]", },
        SnPUpdateUnformatted { date: "June 20, 2018", added_ticker: "FLT", added_security: "FleetCor Technologies", removed_ticker: "TWX", removed_security: "Time Warner ", reason: "AT&T acquired Time Warner.[79]", },
        SnPUpdateUnformatted { date: "June 18, 2018", added_ticker: "BR", added_security: "Broadridge Financial Solutions", removed_ticker: "RRC", removed_security: "Range Resources ", reason: "Market capitalization change.[80]", },
        SnPUpdateUnformatted { date: "June 18, 2018", added_ticker: "HFC", added_security: "HollyFrontier", removed_ticker: "AYI", removed_security: "Acuity Brands ", reason: "Market capitalization change.[80]", },
        SnPUpdateUnformatted { date: "June 7, 2018", added_ticker: "TWTR", added_security: "Twitter", removed_ticker: "MON", removed_security: "Monsanto ", reason: "Bayer acquired Monsanto.[81]", },
        SnPUpdateUnformatted { date: "June 5, 2018", added_ticker: "EVRG", added_security: "Evergy", removed_ticker: "NAVI", removed_security: "Navient ", reason: "Westar Energy (NYSE: WR) acquired Great Plains Energy (NYSE: GXP) and changed name to Evergy.[82]", },
        SnPUpdateUnformatted { date: "May 31, 2018", added_ticker: "ABMD", added_security: "Abiomed", removed_ticker: "WYN", removed_security: "Wyndham Worldwide ", reason: "Wyndham Worldwide spun off Wyndham Hotels & Resorts (NYSE:WH).[83]", },
        SnPUpdateUnformatted { date: "April 4, 2018", added_ticker: "MSCI", added_security: "MSCI", removed_ticker: "CSRA", removed_security: "CSRA ", reason: "S&P 500 constituent General Dynamics (NYSE: GD) acquired CSRA.[84]", },
        SnPUpdateUnformatted { date: "March 19, 2018", added_ticker: "TTWO", added_security: "Take-Two Interactive", removed_ticker: "SIG", removed_security: "Signet Jewelers ", reason: "Market capitalization change.[85]", },
        SnPUpdateUnformatted { date: "March 19, 2018", added_ticker: "SIVB", added_security: "SVB Financial Group", removed_ticker: "PDCO", removed_security: "Patterson Companies ", reason: "Market capitalization change.[85]", },
        SnPUpdateUnformatted { date: "March 19, 2018", added_ticker: "NKTR", added_security: "Nektar Therapeutics", removed_ticker: "CHK", removed_security: "Chesapeake Energy ", reason: "Market capitalization change.[85]", },
        SnPUpdateUnformatted { date: "March 7, 2018", added_ticker: "IPGP", added_security: "IPG Photonics", removed_ticker: "SNI", removed_security: "Scripps Networks Interactive ", reason: "Discovery Communications acquired SNI.[86]", },
        SnPUpdateUnformatted { date: "January 3, 2018", added_ticker: "HII", added_security: "Huntington Ingalls Industries", removed_ticker: "BCR", removed_security: "CR Bard ", reason: "Becton Dickinson acquired BCR.[87]", },
        SnPUpdateUnformatted { date: "October 13, 2017", added_ticker: "NCLH", added_security: "Norwegian Cruise Line Holdings", removed_ticker: "LVLT", removed_security: "Level 3 Communications ", reason: "CenturyLink acquired LVLT.[88]", },
        SnPUpdateUnformatted { date: "September 18, 2017", added_ticker: "CDNS", added_security: "Cadence Design Systems", removed_ticker: "SPLS", removed_security: "Staples ", reason: "Sycamore Partners acquired Staples.[89]", },
        SnPUpdateUnformatted { date: "September 1, 2017", added_ticker: "DWDP", added_security: "DuPont", removed_ticker: "DOW", removed_security: "Dow Chemical Company ", reason: "The Dow Chemical Company renamed to DowDuPont Inc. and ticker changed from DOW to DWDP after acquiring DuPont.[90]", },
        SnPUpdateUnformatted { date: "September 1, 2017", added_ticker: "SBAC", added_security: "SBA Communications", removed_ticker: "DD", removed_security: "DuPont ", reason: "The Dow Chemical Company acquired DuPont.[90]", },
        SnPUpdateUnformatted { date: "August 29, 2017", added_ticker: "Q", added_security: "QuintilesIMS", removed_ticker: "WFM", removed_security: "Whole Foods Market ", reason: "Amazon acquired Whole Foods Market.[90]", },
        SnPUpdateUnformatted { date: "August 8, 2017", added_ticker: "BHF", added_security: "Brighthouse Financial", removed_ticker: "AN", removed_security: "AutoNation ", reason: "BHF replaced AN,[91] MET spun off BHF[91]", },
        SnPUpdateUnformatted { date: "July 26, 2017", added_ticker: "DRE", added_security: "Duke Realty Corp", removed_ticker: "RIG", removed_security: "Transocean ", reason: "Market capitalization change.[92]", },
        SnPUpdateUnformatted { date: "July 26, 2017", added_ticker: "AOS", added_security: "A. O. Smith", removed_ticker: "BBBY", removed_security: "Bed Bath & Beyond ", reason: "Market capitalization change.[92]", },
        SnPUpdateUnformatted { date: "July 26, 2017", added_ticker: "PKG", added_security: "Packaging Corporation of America", removed_ticker: "MUR", removed_security: "Murphy Oil ", reason: "Market capitalization change.[92]", },
        SnPUpdateUnformatted { date: "July 26, 2017", added_ticker: "RMD", added_security: "ResMed", removed_ticker: "MNK", removed_security: "Mallinckrodt ", reason: "Market capitalization change.[92]", },
        SnPUpdateUnformatted { date: "July 26, 2017", added_ticker: "MGM", added_security: "MGM Resorts International", removed_ticker: "RAI", removed_security: "Reynolds American ", reason: "British American Tobacco (NYSE MKT:BTI) acquired Reynolds American.[92]", },
        SnPUpdateUnformatted { date: "June 19, 2017", added_ticker: "HLT", added_security: "Hilton", removed_ticker: "YHOO", removed_security: "Yahoo! ", reason: "VZ acquired YHOO operations; remainder of YHOO converted to closed-end company known as Altaba.[93]", },
        SnPUpdateUnformatted { date: "June 19, 2017", added_ticker: "ALGN", added_security: "Align Technology", removed_ticker: "TDC", removed_security: "Teradata ", reason: "Market capitalization changes.[93]", },
        SnPUpdateUnformatted { date: "June 19, 2017", added_ticker: "ANSS", added_security: "Ansys", removed_ticker: "R", removed_security: "Ryder System ", reason: "Market capitalization changes.[93]", },
        SnPUpdateUnformatted { date: "June 19, 2017", added_ticker: "RE", added_security: "Everest Re", removed_ticker: "MJN", removed_security: "Mead Johnson ", reason: "Reckitt Benckiser acquired Mead Johnson Nutrition.[94]", },
        SnPUpdateUnformatted { date: "June 2, 2017", added_ticker: "INFO", added_security: "IHS Markit", removed_ticker: "TGNA", removed_security: "Tegna ", reason: "TGNA spins off Cars.com[95]", },
        SnPUpdateUnformatted { date: "April 5, 2017", added_ticker: "IT", added_security: "Gartner", removed_ticker: "DNB", removed_security: "Dun & Bradstreet ", reason: "IT acquiring CEB[96]", },
        SnPUpdateUnformatted { date: "April 4, 2017", added_ticker: "DXC", added_security: "DXC Technology", removed_ticker: "SWN", removed_security: "Southwestern Energy ", reason: "HPE spins off Everett, merged with CSC to form DXC[97][98]", },
        SnPUpdateUnformatted { date: "March 20, 2017", added_ticker: "AMD", added_security: "Advanced Micro Devices", removed_ticker: "URBN", removed_security: "Urban Outfitters ", reason: "Market capitalization change.[99]", },
        SnPUpdateUnformatted { date: "March 20, 2017", added_ticker: "RJF", added_security: "Raymond James Financial", removed_ticker: "FTR", removed_security: "Frontier Communications ", reason: "Market capitalization change.[99]", },
        SnPUpdateUnformatted { date: "March 20, 2017", added_ticker: "ARE", added_security: "Alexandria Real Estate Equities", removed_ticker: "FSLR", removed_security: "First Solar ", reason: "Market capitalization change.[99]", },
        SnPUpdateUnformatted { date: "March 16, 2017", added_ticker: "SNPS", added_security: "Synopsys", removed_ticker: "HAR", removed_security: "Harman International ", reason: "Samsung Electronics acquired Harman International Industries.[100]", },
        SnPUpdateUnformatted { date: "March 13, 2017", added_ticker: "DISH", added_security: "Dish Network", removed_ticker: "LLTC", removed_security: "Linear Technology ", reason: "S&P 500 constituent Analog Devices (NASD:ADI) acquired Linear Technology.[101]", },
        SnPUpdateUnformatted { date: "March 2, 2017", added_ticker: "REG", added_security: "Regency Centers", removed_ticker: "ENDP", removed_security: "Endo International ", reason: "REG acquires EQY[102]", },
        SnPUpdateUnformatted { date: "March 1, 2017", added_ticker: "CBOE", added_security: "Cboe Holdings", removed_ticker: "PBI", removed_security: "Pitney Bowes ", reason: "CBOE acquires BATS[102]", },
        SnPUpdateUnformatted { date: "February 28, 2017", added_ticker: "INCY", added_security: "Incyte", removed_ticker: "SE", removed_security: "Spectra Energy ", reason: "SE acquired by ENB[102]", },
        SnPUpdateUnformatted { date: "January 5, 2017", added_ticker: "IDXX", added_security: "Idexx Laboratories", removed_ticker: "STJ", removed_security: "St Jude Medical ", reason: "S&P 100 & 500 constituent Abbott Laboratories (NYSE:ABT) acquired St. Jude Medical.[103]", },
        SnPUpdateUnformatted { date: "December 19, 2016", added_ticker: "AGN", added_security: "Allergan", removed_ticker: "", removed_security: "", reason: "Allergan plc(NYSE:AGN) added to S&P 500 Value", },
        SnPUpdateUnformatted { date: "December 2, 2016", added_ticker: "MAA", added_security: "Mid-America Apartments", removed_ticker: "OI", removed_security: "Owens-Illinois ", reason: "Market capitalization change.[104]", },
        SnPUpdateUnformatted { date: "December 2, 2016", added_ticker: "EVHC", added_security: "Envision Healthcare", removed_ticker: "LM", removed_security: "Legg Mason ", reason: "Market capitalization change.[104]", },
        SnPUpdateUnformatted { date: "November 1, 2016", added_ticker: "ARNC", added_security: "Arconic", removed_ticker: "AA", removed_security: "Alcoa ", reason: "AA spins off ARNC[105]", },
        SnPUpdateUnformatted { date: "September 30, 2016", added_ticker: "COTY", added_security: "Coty", removed_ticker: "DO", removed_security: "Diamond Offshore Drilling ", reason: "COTY replaces DO[106]", },
        SnPUpdateUnformatted { date: "September 22, 2016", added_ticker: "COO", added_security: "The Cooper Companies", removed_ticker: "HOT", removed_security: "Starwood ", reason: "MAR acquires HOT[107]", },
        SnPUpdateUnformatted { date: "September 8, 2016", added_ticker: "CHTR", added_security: "Charter Communications", removed_ticker: "EMC", removed_security: "EMC Corporation ", reason: "Dell acquires EMC[108]", },
        SnPUpdateUnformatted { date: "September 6, 2016", added_ticker: "MTD", added_security: "Mettler Toledo", removed_ticker: "TYC", removed_security: "Tyco International ", reason: "TYC acquires JCI (and retains JCI ticker).[109]", },
        SnPUpdateUnformatted { date: "July 5, 2016", added_ticker: "FTV", added_security: "Fortive Corp", removed_ticker: "CPGX", removed_security: "Columbia Pipeline Group ", reason: "CPGX acquired by TRP[110]", },
        SnPUpdateUnformatted { date: "July 1, 2016", added_ticker: "LNT", added_security: "Alliant Energy Corp", removed_ticker: "GAS", removed_security: "AGL Resources ", reason: "GAS acquired by SO[111]", },
        SnPUpdateUnformatted { date: "July 1, 2016", added_ticker: "ALB", added_security: "Albemarle Corporation", removed_ticker: "TE", removed_security: "TECO Energy ", reason: "TE acquired by EMA[110]", },
        SnPUpdateUnformatted { date: "June 22, 2016", added_ticker: "FBHS", added_security: "Fortune Brands Home & Security", removed_ticker: "CVC", removed_security: "Cablevision Systems ", reason: "CVC acquired by Altice NV[112]", },
        SnPUpdateUnformatted { date: "June 3, 2016", added_ticker: "TDG", added_security: "TransDigm Group", removed_ticker: "BXLT", removed_security: "Baxalta ", reason: "SHPG acquiring BXLT[113]", },
        SnPUpdateUnformatted { date: "May 31, 2016", added_ticker: "AJG", added_security: "Arthur J. Gallagher & Co.", removed_ticker: "CCE", removed_security: "Coca-Cola Enterprises ", reason: "CCE merging with European bottlers[114]", },
        SnPUpdateUnformatted { date: "May 23, 2016", added_ticker: "LKQ", added_security: "LKQ Corporation", removed_ticker: "ARG", removed_security: "Airgas ", reason: "ARG acquired by Air Liquide[115]", },
        SnPUpdateUnformatted { date: "May 18, 2016", added_ticker: "DLR", added_security: "Digital Realty", removed_ticker: "TWC", removed_security: "Time Warner Cable ", reason: "TWC acquired by CHTR[116]", },
        SnPUpdateUnformatted { date: "May 13, 2016", added_ticker: "ALK", added_security: "Alaska Air Group", removed_ticker: "SNDK", removed_security: "SanDisk ", reason: "SNDK acquired by WDC[117]", },
        SnPUpdateUnformatted { date: "May 3, 2016", added_ticker: "AYI", added_security: "Acuity Brands", removed_ticker: "ADT", removed_security: "ADT ", reason: "ADT acquired by APO[118]", },
        SnPUpdateUnformatted { date: "April 25, 2016", added_ticker: "GPN", added_security: "Global Payments", removed_ticker: "GME", removed_security: "GameStop ", reason: "Global Payments is acquiring Heartland Payment Systems[119]", },
        SnPUpdateUnformatted { date: "April 18, 2016", added_ticker: "ULTA", added_security: "Ulta Beauty", removed_ticker: "THC", removed_security: "Tenet Healthcare ", reason: "Ulta replaces Tenet[120]", },
        SnPUpdateUnformatted { date: "April 8, 2016", added_ticker: "UA", added_security: "Under Armour (Class C)", removed_ticker: "", removed_security: "", reason: "Under Armour distribution of second class of stock", },
        SnPUpdateUnformatted { date: "April 4, 2016", added_ticker: "FL", added_security: "Foot Locker", removed_ticker: "CAM", removed_security: "Cameron International ", reason: "Schlumberger acquired Cameron[121]", },
        SnPUpdateUnformatted { date: "March 30, 2016", added_ticker: "HOLX", added_security: "Hologic", removed_ticker: "POM", removed_security: "Pepco Holdings ", reason: "Exelon acquired Pepco.[122]", },
        SnPUpdateUnformatted { date: "March 30, 2016", added_ticker: "CNC", added_security: "Centene Corporation", removed_ticker: "ESV", removed_security: "Ensco ", reason: "Centene acquired Health Net.[122]", },
        SnPUpdateUnformatted { date: "March 7, 2016", added_ticker: "UDR", added_security: "UDR", removed_ticker: "GMCR", removed_security: "Keurig Green Mountain ", reason: "JAB Holding Company acquired Keurig Green Mountain[123]", },
        SnPUpdateUnformatted { date: "March 4, 2016", added_ticker: "AWK", added_security: "American Water Works", removed_ticker: "CNX", removed_security: "Consol Energy ", reason: "AWK replaces CNX[124]", },
        SnPUpdateUnformatted { date: "February 22, 2016", added_ticker: "CXO", added_security: "Concho Resources", removed_ticker: "PCL", removed_security: "Plum Creek Timber ", reason: "PCL taken over by WY[125]", },
        SnPUpdateUnformatted { date: "February 1, 2016", added_ticker: "CFG", added_security: "Citizens", removed_ticker: "PCP", removed_security: "Precision Castparts Corporation ", reason: "CFG replaces PCP[126]", },
        SnPUpdateUnformatted { date: "February 1, 2016", added_ticker: "FRT", added_security: "Federal Realty Investment Trust", removed_ticker: "BRCM", removed_security: "Broadcom Corporation ", reason: "FRT replaces BRCM[127]", },
        SnPUpdateUnformatted { date: "January 19, 2016", added_ticker: "EXR", added_security: "Extra Space Storage", removed_ticker: "ACE", removed_security: "Chubb ", reason: "EXR replaces ACE as ACE Ltd acquires Chubb and retains the CB ticker, giving up ACE[128]", },
        SnPUpdateUnformatted { date: "January 5, 2016", added_ticker: "WLTW", added_security: "Willis Towers Watson", removed_ticker: "FOSL", removed_security: "Fossil Group ", reason: "WSH merges with TW (and renames to WLTW)[129]", },
        SnPUpdateUnformatted { date: "December 29, 2015", added_ticker: "CHD", added_security: "Church & Dwight", removed_ticker: "ALTR", removed_security: "Altera ", reason: "ALTR taken over by INTC[130]", },
        SnPUpdateUnformatted { date: "December 15, 2015", added_ticker: "", added_security: "", removed_ticker: "CMCSK", removed_security: "Comcast K Corp", reason: "CMCSK shares no longer listed[131]", },
        SnPUpdateUnformatted { date: "December 1, 2015", added_ticker: "CSRA", added_security: "CSRA", removed_ticker: "CSC", removed_security: "Computer Sciences Corporation ", reason: "CSC spins off CSRA[132]", },
        SnPUpdateUnformatted { date: "November 19, 2015", added_ticker: "ILMN", added_security: "Illumina", removed_ticker: "SIAL", removed_security: "Sigma-Aldrich ", reason: "Sigma-Aldrich acquired by Merck KGaA (MKGAY)[133]", },
        SnPUpdateUnformatted { date: "November 18, 2015", added_ticker: "SYF", added_security: "Synchrony Financial", removed_ticker: "GNW", removed_security: "Genworth Financial ", reason: "GE spinning off Synchrony Financial[134]", },
        SnPUpdateUnformatted { date: "November 2, 2015", added_ticker: "HPE", added_security: "Hewlett Packard Enterprise", removed_ticker: "HCBK", removed_security: "Hudson City Bancorp ", reason: "HPQ spins off HPE[135]", },
        SnPUpdateUnformatted { date: "October 7, 2015", added_ticker: "VRSK", added_security: "Verisk Analytics", removed_ticker: "JOY", removed_security: "Joy Global ", reason: "Market capitalization change.[136]", },
        SnPUpdateUnformatted { date: "September 18, 2015", added_ticker: "CMCSK", added_security: "Comcast Class K Special", removed_ticker: "", removed_security: "", reason: "Share class methodology change[137]", },
        SnPUpdateUnformatted { date: "September 18, 2015", added_ticker: "FOX", added_security: "Twenty-First Century Fox Class B", removed_ticker: "", removed_security: "", reason: "Share class methodology change", },
        SnPUpdateUnformatted { date: "September 18, 2015", added_ticker: "NWS", added_security: "News Corporation Class B", removed_ticker: "", removed_security: "", reason: "Share class methodology change", },
        SnPUpdateUnformatted { date: "September 2, 2015", added_ticker: "UAL", added_security: "United Continental Holdings", removed_ticker: "HSP", removed_security: "Hospira ", reason: "Hospira taken over[138]", },
        SnPUpdateUnformatted { date: "August 28, 2015", added_ticker: "ATVI", added_security: "Activision Blizzard", removed_ticker: "PLL", removed_security: "Pall Corporation ", reason: "Pall taken over[138]", },
        SnPUpdateUnformatted { date: "July 29, 2015", added_ticker: "SIG", added_security: "Signet Jewelers", removed_ticker: "DTV", removed_security: "DirecTV ", reason: "DirecTV acquired by AT&T.[139]", },
        SnPUpdateUnformatted { date: "July 20, 2015", added_ticker: "PYPL", added_security: "PayPal", removed_ticker: "NE", removed_security: "Noble Corporation ", reason: "PayPal Spun off by eBay[140]", },
        SnPUpdateUnformatted { date: "July 8, 2015", added_ticker: "AAP", added_security: "Advance Auto Parts", removed_ticker: "FDO", removed_security: "Family Dollar ", reason: "Family Dollar acquired.[141]", },
        SnPUpdateUnformatted { date: "July 6, 2015", added_ticker: "KHC", added_security: "Kraft Heinz", removed_ticker: "KRFT", removed_security: "Kraft Foods ", reason: "Kraft merger with Heinz.[142]", },
        SnPUpdateUnformatted { date: "July 2, 2015", added_ticker: "CPGX", added_security: "Columbia Pipeline Group", removed_ticker: "ATI", removed_security: "Allegheny Technologies ", reason: "Spin off of Columbia Pipeline.[143]", },
        SnPUpdateUnformatted { date: "July 1, 2015", added_ticker: "JBHT", added_security: "J.B. Hunt", removed_ticker: "TEG", removed_security: "Integrys Energy Group ", reason: "Integrys taken over.[144]", },
        SnPUpdateUnformatted { date: "July 1, 2015", added_ticker: "BXLT", added_security: "Baxalta", removed_ticker: "QEP", removed_security: "QEP Resources ", reason: "Baxalta spun off by Baxter.[145]", },
        SnPUpdateUnformatted { date: "June 11, 2015", added_ticker: "QRVO", added_security: "Qorvo", removed_ticker: "LO", removed_security: "Lorillard Tobacco Company ", reason: "Lorillard gets acquired.[146]", },
        SnPUpdateUnformatted { date: "April 7, 2015", added_ticker: "O", added_security: "Realty Income Corporation", removed_ticker: "WIN", removed_security: "Windstream Communications ", reason: "Market capitalization change.[147]", },
        SnPUpdateUnformatted { date: "March 23, 2015", added_ticker: "AAL", added_security: "American Airlines Group", removed_ticker: "AGN", removed_security: "Allergan ", reason: "Allergan acquired by Actavis (and changed name to Allergan).[148]", },
        SnPUpdateUnformatted { date: "March 23, 2015", added_ticker: "EQIX", added_security: "Equinix", removed_ticker: "DNR", removed_security: "Denbury Resources ", reason: "Market Capitalization Changes.[149]", },
        SnPUpdateUnformatted { date: "March 23, 2015", added_ticker: "SLG", added_security: "SL Green Realty", removed_ticker: "NBR", removed_security: "Nabors Industries ", reason: "Market Capitalization Changes.", },
        SnPUpdateUnformatted { date: "March 23, 2015", added_ticker: "HBI", added_security: "Hanesbrands", removed_ticker: "AVP", removed_security: "Avon Products ", reason: "Market Capitalization Changes.", },
        SnPUpdateUnformatted { date: "March 18, 2015", added_ticker: "HSIC", added_security: "Henry Schein", removed_ticker: "CFN", removed_security: "Carefusion ", reason: "Carefusion acquired by Becton Dickinson[150]", },
        SnPUpdateUnformatted { date: "March 12, 2015", added_ticker: "SWKS", added_security: "Skyworks", removed_ticker: "PETM", removed_security: "PetSmart ", reason: "PetSmart acquired by private equity consortium[151]", },
        SnPUpdateUnformatted { date: "January 27, 2015", added_ticker: "HCA", added_security: "HCA Holdings", removed_ticker: "SWY", removed_security: "Safeway ", reason: "Safeway acquired by private equity consortium[152]", },
        SnPUpdateUnformatted { date: "January 27, 2015", added_ticker: "ENDP", added_security: "Endo International", removed_ticker: "COV", removed_security: "Covidien ", reason: "Covidien acquired by Medtronic[153]", },
        SnPUpdateUnformatted { date: "December 5, 2014", added_ticker: "RCL", added_security: "Royal Caribbean Cruises", removed_ticker: "BMS", removed_security: "Bemis Company ", reason: "Market cap changes[154]", },
        SnPUpdateUnformatted { date: "November 5, 2014", added_ticker: "LVLT", added_security: "Level 3 Communications", removed_ticker: "JBL", removed_security: "Jabil Circuit ", reason: "Market cap changes[155]", },
        SnPUpdateUnformatted { date: "September 20, 2014", added_ticker: "URI", added_security: "United Rentals", removed_ticker: "BTU", removed_security: "Peabody Energy ", reason: "Market cap changes[156]", },
        SnPUpdateUnformatted { date: "September 20, 2014", added_ticker: "UHS", added_security: "Universal Health Services", removed_ticker: "GHC", removed_security: "Graham Holdings ", reason: "Market cap changes", },
        SnPUpdateUnformatted { date: "August 18, 2014", added_ticker: "MNK", added_security: "Mallinckrodt", removed_ticker: "RDC", removed_security: "Rowan Companies ", reason: "Market cap changes[157]", },
        SnPUpdateUnformatted { date: "August 6, 2014", added_ticker: "DISCK", added_security: "Discovery Communications", removed_ticker: "", removed_security: "", reason: "Class C share distribution[158]", },
        SnPUpdateUnformatted { date: "July 2, 2014", added_ticker: "MLM", added_security: "Martin Marietta", removed_ticker: "X", removed_security: "United States Steel ", reason: "Market capitalization changes[159]", },
        SnPUpdateUnformatted { date: "July 1, 2014", added_ticker: "AMG", added_security: "Affiliated Managers Group", removed_ticker: "FRX", removed_security: "Forest Laboratories ", reason: "Actavis acquires Forest Laboratories[160]", },
        SnPUpdateUnformatted { date: "June 20, 2014", added_ticker: "XEC", added_security: "Cimarex Energy", removed_ticker: "IGT", removed_security: "International Game Technology ", reason: "Market capitalization changes[161]", },
        SnPUpdateUnformatted { date: "May 8, 2014", added_ticker: "AVGO", added_security: "Avago Technologies", removed_ticker: "LSI", removed_security: "LSI Corporation ", reason: "Avago acquires LSI[162]", },
        SnPUpdateUnformatted { date: "May 1, 2014", added_ticker: "UA", added_security: "Under Armour", removed_ticker: "BEAM", removed_security: "Beam Suntory ", reason: "Beam acquired by Suntory[163]", },
        SnPUpdateUnformatted { date: "May 1, 2014", added_ticker: "NAVI", added_security: "Navient", removed_ticker: "SLM", removed_security: "SLM Corporation ", reason: "Navient Spun off from SLM[163]", },
        SnPUpdateUnformatted { date: "April 3, 2014", added_ticker: "GOOGL", added_security: "Google", removed_ticker: "", removed_security: "", reason: "Google Class C share distribution[164]", },
        SnPUpdateUnformatted { date: "April 2, 2014", added_ticker: "ESS", added_security: "Essex Property Trust", removed_ticker: "CLF", removed_security: "Cliffs Natural Resources ", reason: "Market capitalization changes[165]", },
        SnPUpdateUnformatted { date: "March 21, 2014", added_ticker: "GMCR", added_security: "Keurig Green Mountain", removed_ticker: "WPX", removed_security: "WPX Energy ", reason: "Market capitalization changes[166]", },
        SnPUpdateUnformatted { date: "January 24, 2014", added_ticker: "TSCO", added_security: "Tractor Supply", removed_ticker: "LIFE", removed_security: "Life Technologies ", reason: "Life Technologies acquired by Thermo Fisher Scientific Inc[167]", },
        SnPUpdateUnformatted { date: "December 23, 2013", added_ticker: "ADS", added_security: "Alliance Data Systems", removed_ticker: "ANF", removed_security: "Abercrombie & Fitch ", reason: "Market capitalization changes.[168]", },
        SnPUpdateUnformatted { date: "December 23, 2013", added_ticker: "MHK", added_security: "Mohawk Industries", removed_ticker: "JDSU", removed_security: "JDS Uniphase ", reason: "Market capitalization changes.[168]", },
        SnPUpdateUnformatted { date: "December 23, 2013", added_ticker: "FB", added_security: "Facebook", removed_ticker: "TER", removed_security: "Teradyne ", reason: "Market capitalization changes.[168]", },
        SnPUpdateUnformatted { date: "December 10, 2013", added_ticker: "GGP", added_security: "General Growth Properties", removed_ticker: "MOLX", removed_security: "Molex ", reason: "MOLX acquired by Koch Industries.[169]", },
        SnPUpdateUnformatted { date: "December 2, 2013", added_ticker: "ALLE", added_security: "Allegion", removed_ticker: "JCP", removed_security: "JCPenney ", reason: "Allegion spun off by Ingersoll Rand.[170]", },
        SnPUpdateUnformatted { date: "November 13, 2013", added_ticker: "KORS", added_security: "Michael Kors", removed_ticker: "NYX", removed_security: "NYSE Euronext ", reason: "ICE Exchange acquired NYSE Euronext.[171]", },
        SnPUpdateUnformatted { date: "October 29, 2013", added_ticker: "RIG", added_security: "Transocean", removed_ticker: "DELL", removed_security: "Dell ", reason: "Founder Michael Dell and Silver Lake Partners acquired Dell.[172]", },
        SnPUpdateUnformatted { date: "September 20, 2013", added_ticker: "VRTX", added_security: "Vertex Pharmaceuticals", removed_ticker: "AMD", removed_security: "Advanced Micro Devices ", reason: "Market capitalization change.[173]", },
        SnPUpdateUnformatted { date: "September 20, 2013", added_ticker: "AME", added_security: "Ametek", removed_ticker: "SAI", removed_security: "SAIC ", reason: "Market capitalization change.[173]", },
        SnPUpdateUnformatted { date: "September 10, 2013", added_ticker: "DAL", added_security: "Delta Air Lines", removed_ticker: "BMC", removed_security: "BMC Software ", reason: "BMC taken private by consortium[174]", },
        SnPUpdateUnformatted { date: "July 8, 2013", added_ticker: "NLSN", added_security: "Nielsen Holdings", removed_ticker: "S", removed_security: "Sprint Nextel ", reason: "Softbank consortium purchase results in public float below 50%[175]", },
        SnPUpdateUnformatted { date: "July 1, 2013", added_ticker: "NWSA", added_security: "21st Century Fox", removed_ticker: "APOL", removed_security: "Apollo Education Group ", reason: "Apollo Group's market cap more representative of a mid-cap[176]", },
        SnPUpdateUnformatted { date: "June 21, 2013", added_ticker: "ZTS", added_security: "Zoetis", removed_ticker: "FHN", removed_security: "First Horizon ", reason: "Zoetis spun off by Pfizer[177]", },
        SnPUpdateUnformatted { date: "June 6, 2013", added_ticker: "GM", added_security: "General Motors", removed_ticker: "HNZ", removed_security: "Heinz ", reason: "HNZ acquired by consortium[178]", },
        SnPUpdateUnformatted { date: "May 23, 2013", added_ticker: "KSU", added_security: "Kansas City Southern", removed_ticker: "DF", removed_security: "Dean Foods ", reason: "DF too small after spinoff of White Wave Foods[179]", },
        SnPUpdateUnformatted { date: "May 8, 2013", added_ticker: "MAC", added_security: "Macerich", removed_ticker: "CVH", removed_security: "Coventry Health Care ", reason: "Acquired by Aetna (AET)[180]", },
        SnPUpdateUnformatted { date: "April 30, 2013", added_ticker: "REGN", added_security: "Regeneron Pharmaceuticals", removed_ticker: "PCS", removed_security: "MetroPCS ", reason: "A majority of MetroPCS was acquired by T-Mobile[181]", },
        SnPUpdateUnformatted { date: "February 15, 2013", added_ticker: "PVH", added_security: "PVH", removed_ticker: "BIG", removed_security: "Big Lots ", reason: "Market capitalization changes[182]", },
        SnPUpdateUnformatted { date: "January 2, 2013", added_ticker: "ABBV", added_security: "AbbVie", removed_ticker: "FII", removed_security: "Federated Investors ", reason: "ABBV spun off from Abbott Labs (ABT)[183]", },
        SnPUpdateUnformatted { date: "December 21, 2012", added_ticker: "DLPH", added_security: "Delphi Automotive", removed_ticker: "TIE", removed_security: "Titanium Metals ", reason: "TIE acquired by Precision Cast Parts (PCP)[184]", },
        SnPUpdateUnformatted { date: "December 11, 2012", added_ticker: "GRMN", added_security: "Garmin", removed_ticker: "RRD", removed_security: "RR Donnelley ", reason: "Market capitalization changes[185]", },
        SnPUpdateUnformatted { date: "December 3, 2012", added_ticker: "DG", added_security: "Dollar General", removed_ticker: "CBE", removed_security: "Cooper Industries ", reason: "Acquired by Eaton Corp. (ETN)[186]", },
        SnPUpdateUnformatted { date: "October 10, 2012", added_ticker: "PETM", added_security: "PetSmart", removed_ticker: "SUN", removed_security: "Sunoco ", reason: "Acquired by Energy Transfer Partners (ETP)[187]", },
        SnPUpdateUnformatted { date: "October 2, 2012", added_ticker: "KRFT", added_security: "Kraft Foods", removed_ticker: "ANR", removed_security: "Alpha Natural Resources ", reason: "Kraft split into two companies[188]", },
        SnPUpdateUnformatted { date: "October 1, 2012", added_ticker: "ADT", added_security: "ADT", removed_ticker: "LXK", removed_security: "Lexmark ", reason: "Tyco spun off ADT[189]", },
        SnPUpdateUnformatted { date: "October 1, 2012", added_ticker: "PNR", added_security: "Pentair", removed_ticker: "DV", removed_security: "DeVry ", reason: "Tyco spin-off merged w/Pentair[189]", },
        SnPUpdateUnformatted { date: "September 5, 2012", added_ticker: "LYB", added_security: "LyondellBasell", removed_ticker: "SHLD", removed_security: "Sears Holdings ", reason: "SHLD below public float threshold[190]", },
        SnPUpdateUnformatted { date: "July 31, 2012", added_ticker: "ESV", added_security: "Ensco", removed_ticker: "GR", removed_security: "Goodrich Corporation ", reason: "Goodrich acquired by United Technologies (UTX).[191]", },
        SnPUpdateUnformatted { date: "July 2, 2012", added_ticker: "STX", added_security: "Seagate Technology", removed_ticker: "PGN", removed_security: "Progress Energy ", reason: "Acquired by Duke Energy (DUK)[192]", },
        SnPUpdateUnformatted { date: "June 29, 2012", added_ticker: "MNST", added_security: "Monster Beverage", removed_ticker: "SLE", removed_security: "Sara Lee Corporation ", reason: "Split up of Sara Lee[193]", },
        SnPUpdateUnformatted { date: "June 5, 2012", added_ticker: "LRCX", added_security: "Lam Research", removed_ticker: "NVLS", removed_security: "Novellus Systems ", reason: "Acquired by Lam Research (LRCX)[194]", },
        SnPUpdateUnformatted { date: "May 21, 2012", added_ticker: "ALXN", added_security: "Alexion Pharmaceuticals", removed_ticker: "MMI", removed_security: "Motorola Mobility ", reason: "Acquired by Google (GOOG)[195]", },
        SnPUpdateUnformatted { date: "May 17, 2012", added_ticker: "KMI", added_security: "Kinder Morgan", removed_ticker: "EP", removed_security: "El Paso Corporation ", reason: "Acquired by Kinder Morgan (KMI)[196]", },
        SnPUpdateUnformatted { date: "April 23, 2012", added_ticker: "PSX", added_security: "Phillips 66", removed_ticker: "SVU", removed_security: "Supervalu ", reason: "ConocoPhillips spun off Phillips 66[197]", },
        SnPUpdateUnformatted { date: "April 3, 2012", added_ticker: "FOSL", added_security: "Fossil", removed_ticker: "MHS", removed_security: "Medco Health Solutions ", reason: "Acquired by Express Scripts (ESRX)[198]", },
        SnPUpdateUnformatted { date: "March 13, 2012", added_ticker: "CCI", added_security: "Crown Castle", removed_ticker: "CEG", removed_security: "Constellation Energy Group ", reason: "Acquired by Exelon Corp. (EXC)[199]", },
        SnPUpdateUnformatted { date: "December 31, 2011", added_ticker: "WPX", added_security: "WPX Energy", removed_ticker: "CPWR", removed_security: "Compuware ", reason: "Market capitalization changes[200]", },
        SnPUpdateUnformatted { date: "December 20, 2011", added_ticker: "TRIP", added_security: "TripAdvisor", removed_ticker: "TLAB", removed_security: "Tellabs ", reason: "Expedia spun off TripAdvisor.[201]", },
        SnPUpdateUnformatted { date: "December 16, 2011", added_ticker: "BWA", added_security: "BorgWarner", removed_ticker: "AKS", removed_security: "AK Steel ", reason: "Market capitalization changes[202]", },
        SnPUpdateUnformatted { date: "December 16, 2011", added_ticker: "PRGO", added_security: "Perrigo", removed_ticker: "MWW", removed_security: "Monster Worldwide ", reason: "Market capitalization changes", },
        SnPUpdateUnformatted { date: "December 16, 2011", added_ticker: "DLTR", added_security: "Dollar Tree", removed_ticker: "WFR", removed_security: "MEMC Electronic Materials ", reason: "Market capitalization changes", },
        SnPUpdateUnformatted { date: "December 12, 2011", added_ticker: "GAS", added_security: "AGL Resources.", removed_ticker: "GAS", removed_security: "Nicor Gas ", reason: "Nicor acquired by AGL, which retained the GAS ticker.[203]", },
        SnPUpdateUnformatted { date: "November 18, 2011", added_ticker: "CBE", added_security: "Cooper Industries", removed_ticker: "JNS", removed_security: "Janus Capital Group ", reason: "Janus Capital Group's market capitalization is less than $1.2 billion, and is no longer representative of the large cap market space.[204]", },
        SnPUpdateUnformatted { date: "October 31, 2011", added_ticker: "XYL", added_security: "Xylem", removed_ticker: "ITT", removed_security: "ITT ", reason: "Spun off from ITT Corp.[205]", },
        SnPUpdateUnformatted { date: "October 14, 2011", added_ticker: "TEL", added_security: "TE Connectivity", removed_ticker: "CEPH", removed_security: "Cephalon ", reason: "Acquired by Teva Pharmaceutical Industries (TEVA).[206]", },
        SnPUpdateUnformatted { date: "September 23, 2011", added_ticker: "MOS", added_security: "The Mosaic Company", removed_ticker: "NSM", removed_security: "National Semiconductor ", reason: "Acquired by Texas Instruments (TXN).[207]", },
        SnPUpdateUnformatted { date: "July 5, 2011", added_ticker: "ACN", added_security: "Accenture", removed_ticker: "MI", removed_security: "Marshall & Ilsley ", reason: "Marshall & Iisley is being bought by Bank of Montreal[208]", },
        SnPUpdateUnformatted { date: "June 30, 2011", added_ticker: "MPC", added_security: "Marathon Oil", removed_ticker: "RSH", removed_security: "RadioShack ", reason: "Market capitalization adjustments.[209]", },
        SnPUpdateUnformatted { date: "June 1, 2011", added_ticker: "ANR", added_security: "Alpha Natural Resources", removed_ticker: "MEE", removed_security: "Massey Energy ", reason: "Alpha Natural Resources acquired Massey Energy.[210]", },
        SnPUpdateUnformatted { date: "April 27, 2011", added_ticker: "CMG", added_security: "Chipotle Mexican Grill", removed_ticker: "NOVL", removed_security: "Novell ", reason: "Acquired by private equity firms.[211]", },
        SnPUpdateUnformatted { date: "April 1, 2011", added_ticker: "BLK", added_security: "BlackRock", removed_ticker: "GENZ", removed_security: "Genzyme ", reason: "Acquired by Sanofi Aventis (SNY)[212]", },
        SnPUpdateUnformatted { date: "March 31, 2011", added_ticker: "EW", added_security: "Edwards Lifesciences", removed_ticker: "Q", removed_security: "Qwest Communications ", reason: "Acquired by CenturyLink[213]", },
        SnPUpdateUnformatted { date: "February 28, 2011", added_ticker: "COV", added_security: "Covidien", removed_ticker: "MFE", removed_security: "McAfee ", reason: "Acquired by Intel[214]", },
        SnPUpdateUnformatted { date: "February 25, 2011", added_ticker: "JOYG", added_security: "Joy Global", removed_ticker: "AYE", removed_security: "Allegheny Energy ", reason: "Acquired by First Energy (FE).[215]", },
        SnPUpdateUnformatted { date: "December 17, 2010", added_ticker: "CVC", added_security: "Cablevision", removed_ticker: "KG", removed_security: "King Pharmaceuticals ", reason: "Acquired by Pfizer.[216]", },
        SnPUpdateUnformatted { date: "December 17, 2010", added_ticker: "FFIV", added_security: "F5 Networks", removed_ticker: "EK", removed_security: "Eastman Kodak ", reason: "Market Cap changes.[216]", },
        SnPUpdateUnformatted { date: "December 17, 2010", added_ticker: "NFLX", added_security: "Netflix", removed_ticker: "ODP", removed_security: "Office Depot ", reason: "Market Cap changes.", },
        SnPUpdateUnformatted { date: "December 17, 2010", added_ticker: "NFX", added_security: "Newfield Exploration", removed_ticker: "NYT", removed_security: "The New York Times Company ", reason: "Market Cap changes.", },
        SnPUpdateUnformatted { date: "November 17, 2010", added_ticker: "IR", added_security: "Ingersoll-Rand", removed_ticker: "PTV", removed_security: "Pactiv ", reason: "Reynolds Group Holdings acquired Pactiv.[217]", },
        SnPUpdateUnformatted { date: "August 26, 2010", added_ticker: "TYC", added_security: "Tyco International", removed_ticker: "SII", removed_security: "Smith International ", reason: "Acquired by Schlumberger (SLB)[218]", },
        SnPUpdateUnformatted { date: "July 14, 2010", added_ticker: "CB", added_security: "Chubb", removed_ticker: "MIL", removed_security: "Millipore ", reason: "Acquired by Merck KGaA (MKGAY)[219]", },
        SnPUpdateUnformatted { date: "June 30, 2010", added_ticker: "QEP", added_security: "QEP Resources", removed_ticker: "STR", removed_security: "Questar ", reason: "Company split. QEP retained, but ticker changed.[220]", },
        SnPUpdateUnformatted { date: "June 28, 2010", added_ticker: "KMX", added_security: "CarMax", removed_ticker: "XTO", removed_security: "XTO Energy ", reason: "Acquired by ExxonMobil[221]", },
        SnPUpdateUnformatted { date: "April 29, 2010", added_ticker: "CERN", added_security: "Cerner", removed_ticker: "BJS", removed_security: "BJ Services ", reason: "Acquired by Baker Hughes[222]", },
        SnPUpdateUnformatted { date: "February 26, 2010", added_ticker: "HP", added_security: "Helmerich & Payne", removed_ticker: "RX", removed_security: "IMS Health ", reason: "Taken private[223]", },
        SnPUpdateUnformatted { date: "December 18, 2009", added_ticker: "V", added_security: "Visa", removed_ticker: "CIEN", removed_security: "Ciena ", reason: "Market capitalization change.[224]", },
        SnPUpdateUnformatted { date: "December 18, 2009", added_ticker: "MJN", added_security: "Mead Johnson Nutrition", removed_ticker: "DYN", removed_security: "Dynegy ", reason: "Market capitalization change.[224]", },
        SnPUpdateUnformatted { date: "December 18, 2009", added_ticker: "CLF", added_security: "Cliffs Natural Resources", removed_ticker: "KBH", removed_security: "KB Home ", reason: "Market capitalization change.[224]", },
        SnPUpdateUnformatted { date: "December 18, 2009", added_ticker: "SAI", added_security: "SAIC", removed_ticker: "CVG", removed_security: "Convergys ", reason: "Market capitalization change.[224]", },
        SnPUpdateUnformatted { date: "December 18, 2009", added_ticker: "ROST", added_security: "Ross Stores", removed_ticker: "MBI", removed_security: "MBIA ", reason: "Market capitalization change.[224]", },
        SnPUpdateUnformatted { date: "November 3, 2009", added_ticker: "PCLN", added_security: "Priceline.com", removed_ticker: "SGP", removed_security: "Schering-Plough ", reason: "Acquired by Merck & Co. (MRK)[225]", },
        SnPUpdateUnformatted { date: "September 28, 2009", added_ticker: "ARG", added_security: "Airgas", removed_ticker: "CBE", removed_security: "Cooper Industries ", reason: "Redomesticated to Ireland[226]", },
        SnPUpdateUnformatted { date: "August 19, 2009", added_ticker: "FMC", added_security: "FMC Corporation", removed_ticker: "CTX", removed_security: "Centex Corp. ", reason: "Centex acquired by Pulte Homes.[227]", },
        SnPUpdateUnformatted { date: "June 29, 2009", added_ticker: "PCS", added_security: "MetroPCS", removed_ticker: "", removed_security: "", reason: "PCS replaced TEL. [228]", },
        SnPUpdateUnformatted { date: "June 25, 2009", added_ticker: "", added_security: "", removed_ticker: "TEL", removed_security: "TE Connectivity", reason: "Tyco Electronics left the index because it was reincorporating in Switzerland, making it ineligible for inclusion. [228]", },
        SnPUpdateUnformatted { date: "June 5, 2009", added_ticker: "FTI", added_security: "FMC Technologies", removed_ticker: "COV", removed_security: "Covidien ", reason: "Covidien moved its place of incorporation to Ireland, making it ineligible for inclusion in the index.[229]", },
        SnPUpdateUnformatted { date: "March 3, 2009", added_ticker: "HRL", added_security: "Hormel Foods", removed_ticker: "ACAS", removed_security: "American Capital ", reason: "Capitalization rebalance.[230]", },
        SnPUpdateUnformatted { date: "March 3, 2009", added_ticker: "VTR", added_security: "Ventas", removed_ticker: "JNY", removed_security: "Jones Apparel Group ", reason: "Capitalization rebalance.", },
        SnPUpdateUnformatted { date: "December 31, 2008", added_ticker: "OI", added_security: "Owens-Illinois", removed_ticker: "WB", removed_security: "Wachovia Bank ", reason: "Wachovia Bank acquired by Wells Fargo.[231]", },
        SnPUpdateUnformatted { date: "September 16, 2008", added_ticker: "HRS", added_security: "Harris Corporation", removed_ticker: "LEH", removed_security: "Lehman Brothers ", reason: "Lehman Brothers filed for bankruptcy.[232]", },
        SnPUpdateUnformatted { date: "September 12, 2008", added_ticker: "CRM", added_security: "Salesforce", removed_ticker: "FRE", removed_security: "Freddie Mac ", reason: "Capitalization rebalance.[233]", },
        SnPUpdateUnformatted { date: "September 12, 2008", added_ticker: "FAST", added_security: "Fastenal", removed_ticker: "FNM", removed_security: "Fannie Mae ", reason: "Capitalization rebalance.[233]", },
        SnPUpdateUnformatted { date: "July 1, 2008", added_ticker: "AKS", added_security: "AK Steel", removed_ticker: "CFC", removed_security: "Countrywide Financial Corp ", reason: "Ak Steel replaced Countrywide Financial.[234]", },
        SnPUpdateUnformatted { date: "June 23, 2008", added_ticker: "COG", added_security: "Cabot Oil & Gas", removed_ticker: "BC", removed_security: "Brunswick ", reason: "Market capitalization change.[235]", },
        SnPUpdateUnformatted { date: "June 23, 2008", added_ticker: "MEE", added_security: "Massey Energy", removed_ticker: "OMX", removed_security: "OfficeMax ", reason: "Market capitalization change.[235]", },
        SnPUpdateUnformatted { date: "June 10, 2008", added_ticker: "LO", added_security: "Lorillard Tobacco Company", removed_ticker: "ABK", removed_security: "Ambac Financial ", reason: "Market Value Decline[236]", },
        SnPUpdateUnformatted { date: "December 20, 2007", added_ticker: "RRC", added_security: "Range Resources", removed_ticker: "TRB", removed_security: "Tribune Media ", reason: "Taken private[237]", },
        SnPUpdateUnformatted { date: "December 13, 2007", added_ticker: "GME", added_security: "GameStop", removed_ticker: "DJ", removed_security: "Dow Jones ", reason: "Acquired by News Corporation[238]", },
        SnPUpdateUnformatted { date: "October 26, 2007", added_ticker: "JEC", added_security: "Jacobs Engineering Group", removed_ticker: "AV", removed_security: "Avaya ", reason: "Taken private[239]", },
        SnPUpdateUnformatted { date: "October 2, 2007", added_ticker: "EXPE", added_security: "Expedia", removed_ticker: "SLR", removed_security: "Solectron ", reason: "Solectron acquired by Flextronics.[240]", },
        SnPUpdateUnformatted { date: "October 1, 2007", added_ticker: "TDC", added_security: "Teradata", removed_ticker: "NCR", removed_security: "NCR Corporation ", reason: "Teradata spun off by NCR Corporation.[240]", },
        SnPUpdateUnformatted { date: "September 27, 2007", added_ticker: "TSO", added_security: "Tesoro Corporation", removed_ticker: "MXIM", removed_security: "Maxim Integrated Products ", reason: "MXIM delisted from NASDAQ exchange.[240]", },
        SnPUpdateUnformatted { date: "September 26, 2007", added_ticker: "ICE", added_security: "Intercontinental Exchange", removed_ticker: "FDC", removed_security: "First Data ", reason: "FDC acquired by KKR.[240]", },
        SnPUpdateUnformatted { date: "August 24, 2007", added_ticker: "LUK", added_security: "Leucadia National", removed_ticker: "KSE", removed_security: "KeySpan ", reason: "Acquired by National Grid plc[241]", },
        SnPUpdateUnformatted { date: "July 2, 2007", added_ticker: "DFS", added_security: "Discover Financial Services", removed_ticker: "", removed_security: "", reason: "Discover Financial Services Debuts On New York Stock Exchange Under Ticker Symbol DFS", },
        SnPUpdateUnformatted { date: "March 30, 2007", added_ticker: "KFT", added_security: "Kraft Foods", removed_ticker: "TSG", removed_security: "Sabre Corporation ", reason: "Taken Private[242]", },
        SnPUpdateUnformatted { date: "January 10, 2007", added_ticker: "AVB", added_security: "AvalonBay Communities", removed_ticker: "SBL", removed_security: "Symbol Technologies ", reason: "Acquired by Motorola[243]", },
        SnPUpdateUnformatted { date: "June 2, 2006", added_ticker: "JNPR", added_security: "Juniper Networks", removed_ticker: "ABS", removed_security: "Albertsons ", reason: "Albertsons acquired by SuperValu and CVS Corp.[244]", },
        SnPUpdateUnformatted { date: "November 18, 2005", added_ticker: "AMZN", added_security: "Amazon", removed_ticker: "T", removed_security: "AT&T Corporation ", reason: "AT&T Corp. acquired by SBC Communications[245]", },
        SnPUpdateUnformatted { date: "July 1, 2005", added_ticker: "STZ", added_security: "Constellation Brands", removed_ticker: "GLK", removed_security: "Great Lakes Chemical ", reason: "Acquired by Crompton Corp.[246]", },
        SnPUpdateUnformatted { date: "September 25, 2003", added_ticker: "ESRX", added_security: "Express Scripts", removed_ticker: "QTRN", removed_security: "Quintiles Transnational ", reason: "Taken private[247]", },
        SnPUpdateUnformatted { date: "December 5, 2000", added_ticker: "INTU", added_security: "Intuit", removed_ticker: "BS", removed_security: "Bethlehem Steel ", reason: "Market Cap changes.[248]", },
        SnPUpdateUnformatted { date: "December 5, 2000", added_ticker: "SBL", added_security: "Symbol Technologies", removed_ticker: "OI", removed_security: "Owens-Illinois ", reason: "Market Cap changes.", },
        SnPUpdateUnformatted { date: "December 5, 2000", added_ticker: "AYE", added_security: "Allegheny Energy", removed_ticker: "GRA", removed_security: "WR Grace ", reason: "Market Cap changes.", },
        SnPUpdateUnformatted { date: "December 5, 2000", added_ticker: "ABK", added_security: "Ambac Financial", removed_ticker: "CCK", removed_security: "Crown Holdings ", reason: "Market Cap changes.", },
        SnPUpdateUnformatted { date: "July 27, 2000", added_ticker: "JDSU", added_security: "JDS Uniphase", removed_ticker: "RAD", removed_security: "RiteAid ", reason: "Market Cap change.[249]", },
        SnPUpdateUnformatted { date: "June 12, 2000", added_ticker: "CVG", added_security: "Convergys", removed_ticker: "TMC", removed_security: "Times Mirror ", reason: "Tribune Co. acquired Times Mirror.[250]", },
        SnPUpdateUnformatted { date: "June 7, 2000", added_ticker: "SBUX", added_security: "Starbucks", removed_ticker: "SMS", removed_security: "Shared Medical Systems ", reason: "Siemens AG acquired Shared Medical Systems.[250]", },
        SnPUpdateUnformatted { date: "December 7, 1999", added_ticker: "YHOO", added_security: "Yahoo!", removed_ticker: "LDW", removed_security: "Laidlaw ", reason: "Market capitalization change.[251]", },
        SnPUpdateUnformatted { date: "June 9, 1999", added_ticker: "WLP", added_security: "Wellpoint", removed_ticker: "HPH", removed_security: "Harnischfeger Industries ", reason: "Harnischfeger filed for bankruptcy.[252]", },
        SnPUpdateUnformatted { date: "December 11, 1998", added_ticker: "FSR", added_security: "Firstar", removed_ticker: "LDW", removed_security: "Amoco ", reason: "BP purchased Amoco.[253]", },
        SnPUpdateUnformatted { date: "December 11, 1998", added_ticker: "CCL", added_security: "Carnival Corp.", removed_ticker: "GRN", removed_security: "General Re ", reason: "Berkshire Hathaway purchased General Re.[253]", },
        SnPUpdateUnformatted { date: "December 11, 1998", added_ticker: "CPWR", added_security: "Compuware", removed_ticker: "SUN", removed_security: "SunAmerica ", reason: "AIG purchased SunAmerica.[253]", },
        SnPUpdateUnformatted { date: "June 17, 1997", added_ticker: "CCI", added_security: "Countrywide Credit Industries", removed_ticker: "USL", removed_security: "USLife ", reason: "AIG acquired USLife.[254]", },
    ];
    updates_unformatted
}
